steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vishal-gdg-workshop/vishal-gdg-cloudrun:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vishal-gdg-workshop/vishal-gdg-cloudrun:$SHORT_SHA']
